spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/v1/content/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/library/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/libraryContent/**
      discovery:
        locator:
          enabled: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"