spring:
  application:
    name: gateway-service
  cloud:
    gateway:

      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/content/**

        - id: library-service-create
          uri: lb://library-service
          predicates:
            - Path=/api/list/**

        - id: library-service-contents
          uri: lb://library-service
          predicates:
            - Path=/api/list/content/**

        - id: authentication-service-admin
          uri: lb://authentication-service
          predicates:
            - Path=/api/admin/**

        - id: authentication-service-auth
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

        - id: authentication-service-users
          uri: lb://authentication-service
          predicates:
            - Path=/api/users/**

      discovery:
        locator:
          enabled: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt_private_key: "MIICXAIBAAKBgQDBMFAL8jtqkdEkdPBAtp95rxsrttmKTjQ/vo7z0GJD6lNTy6bNiPBiPTKBH6rR5eT7/0DS5RtZQG9VwpOOnFf3jBCBaHRD+PByny1dVjI/9ukM9B+FEuHNH0nE/qdRuA+nFgIKgNvDX65uevgi2N3R5laTpa+wDK49XbZirnZVgwIDAQABAoGAXIEawy2hH71kzLUl2YbYw/aB5yOt9NjPkfpYDw0oEGcisUwhuecpW5D8HvIf5FPVmoi17IYB23HMHd+GslHQmIW9E5SS3+h6qYmfIEDPuhAVKzmn0hrozQR0Bu8gD174PxW7P4z0U3iFitIQQmczzB/G3usGD79lJa2yMkfUcckCQQDuff8nkjHA4ritq666DITTHPlDiIeBr25q32OSwIOdWfyTKYrrwrfBUNO57ExyYBAqrVYlmqakucs64VpnVQFPAkEAz17spn4zDR1MqL3hJ/0U6wJCLrvIvUxxYDoGrla54YKfS1hvVJZBiv2iIcfjKd506hyV/SZM7sFYQsNH+UhTjQJBALWLdA/LWdRawfpyFi/KF9Ic3CJsa7pssMDqDAJKSeYd+gaMORP+xaKCxKljF055kdTq3gkCEJiUVgAcS5UdQEECQEoKsqSf2sqL85sscQA+NQHURJ07H2m3qaOaFFibTrNeWFImuVmSbMSb2xAEtu90JnqQyl0hF8cH8eOkpkYztOECQBWvv8J9QCPsdH0YKvxSWNwL3G9F/dGHwEu/0RxyIqKNlYDRzq5zKn2p+XQANMbcuSe3tnEPH9tJ3TGLBygZPrI="
